#!/usr/bin/env python
""" Executable for the GUI interface of gogonlinux project. """

from gog_utils import gog_gui
from gog_utils import gog_conn

connection = gog_conn.GogConnection()
program = gog_gui.GogTuxGUI(connection)
program.main()
