.TH gog-installer 1 "05 January 2013"
.SH NAME
gog-installer - command line tool for managing www.gogonlinux.com games
.SH SYNOPS
.B gog-installer [OPTIONS] [COMMAND] game_id
.SH DESCRIPTION
gog-installer is a tool used to install/uninstall and launch games downloaded
from gog.com and ported to Linux from the gogonlinux project. You simply run it
from the command line with the appropriate command (no command means to install)
and the game_id (taken from gogonlinux.com)
.SH OPTIONS
.TP 5
.B --token=<token> 
The secret authorization token if you have already authenticated through
gog.com online API.
.TP
.B --secret=<secret>
The secret authorization key if you have already authenticated through 
gog.com online API.
.TP
.B --install-path=<path> 
The path where you want to install the selected game.
.TP 
.B --setup=<setup.exe> 
The path of the already downloaded setup.exe file if you do not want to 
download one from gog.com.
.TP
.B --beta
This enables support for beta (not yet officially released) gogonlinux games.
.TP
.B --force
This forces the installer to use dummy game data (no installer/launcher) in 
order to install the game if the game is not supported by the official
repository.
.TP
.B -p, --private-repo=<repository>
This instructs the intaller to look for a different game repository and not use
the official one.
.SH COMMANDS
.TP 5
.B -h, --help
Displays the usage text in the appplication
.TP
.B -u, --uninstall
Used to uninstall a given game id from the local database of installed games
.TP
.B -r, --run
Used to run a game without having to change to the game's install directory
.TP
.B --version
Displays the version of the software
.TP
.B --list
Shows a list of all the installed games in the local database
.TP
.B --available
Shows a list of all the available games found in the gogonlinux project
.SH AUTHOR
This software is part of the gogonlinux.com project created by 
Morgawr, <
.I morgawr@gmail.com
>
